# Generated by Django 3.2.7 on 2021-09-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generos_e_tipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('lancamento', models.DateField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=2)),
                ('descricao', models.TextField(blank=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generos_e_tipos.genero')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generos_e_tipos.tipo')),
            ],
        ),
    ]
