# Generated by Django 3.2.7 on 2021-09-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midias', '0001_initial'),
        ('generos_e_tipos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genero',
            new_name='Generos',
        ),
        migrations.RenameModel(
            old_name='Tipo',
            new_name='Tipos',
        ),
    ]
